# Generated by Django 4.1.5 on 2023-02-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Comment',
            new_name='comment',
        ),
    ]
